### ISSUE TITLE
[PRE REVIEW]: Testing 1-2-3.

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#1]
**Submitting author:** @emdupre (<a href="http://orcid.org/0000-0003-1358-196X">Elizabeth DuPre</a>)
**Repository:** <a href="https://github.com/brainhack101/introML" target ="_blank">https://github.com/brainhack101/introML</a>
**Editor:** @pbellec
**Reviewers:** @agahkarakuzu, @anibalsolon
**Managing EiC:** Elizabeth DuPre

**Author instructions**

Thanks for submitting your paper to NeuroLibre @emdupre.

@emdupre if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://tinyurl.com/y22xx6ux) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@whedon commands

**Comment by emdupre** [comment]
@whedon commands

**Comment by emdupre** [comment]
@whedon commands

**Comment by emdupre** [comment]
(So sorry to everyone watching this repo)

@roboneuro commands

**Comment by agahkarakuzu** [comment]
I think we all love it, looking forward to roboneuro saying its first words :)

**Comment by emdupre** [comment]
@roboneuro commands

**Comment by emdupre** [comment]
@roboneuro commands

**Comment by roboneuro** [comment]
Here are some things you can ask me to do:

```
# List all of RoboNeuro's capabilities
@roboneuro commands

# Assign a GitHub user as the sole reviewer of this submission
@roboneuro assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@roboneuro add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@roboneuro re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@roboneuro remove @username as reviewer

# List of editor GitHub usernames
@roboneuro list editors

# List of reviewers together with programming language preferences and domain expertise
@roboneuro list reviewers

# Change editorial assignment
@roboneuro assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@roboneuro set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@roboneuro set v1.0.1 as version

# Open the review issue
@roboneuro start review

EDITORIAL TASKS

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@roboneuro remind @reviewer in 2 weeks

# Ask RoboNeuro to do a dry run of accepting the paper and depositing with Crossref
@roboneuro accept

# Ask RoboNeuro to check the references for missing DOIs
@roboneuro check references

# Ask RoboNeuro to check repository statistics for the submitted software
@roboneuro check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@roboneuro invite @editor as editor

# Reject a paper
@roboneuro reject

# Withdraw a paper
@roboneuro withdraw

# Ask RoboNeuro to actually accept the paper and deposit with Crossref
@roboneuro accept deposit=true

```

**Comment by agahkarakuzu** [comment]
👏 congrats @emdupre !

**Comment by rmarkello** [comment]
@roboneuro commands

**Comment by roboneuro** [comment]
Here are some things you can ask me to do:

```
# List RoboNeuro's capabilities
@roboneuro commands

# List of editor GitHub usernames
@roboneuro list editors

# List of reviewers together with programming language preferences and domain expertise
@roboneuro list reviewers

EDITORIAL TASKS

# Compile the paper
@roboneuro generate pdf

# Compile the paper from alternative branch
@roboneuro generate pdf from branch custom-branch-name

# Ask RoboNeuro to check the references for missing DOIs
@roboneuro check references

# Ask RoboNeuro to check repository statistics for the submitted software
@roboneuro check repository

```

**Comment by rmarkello** [comment]
@roboneuro add @emdupre as reviewer

**Comment by agahkarakuzu** [comment]
@roboneuro list reviewers

**Comment by roboneuro** [comment]
I'm sorry @rmarkello, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by roboneuro** [comment]
Here's the current list of reviewers: https://tinyurl.com/y22xx6ux

**Comment by agahkarakuzu** [comment]
@roboneuro list editors

**Comment by roboneuro** [comment]
Current editors:

```
@emdupre
@mathieuboudreau
@pbellec
@roboneuro
```

**Comment by emdupre** [comment]
@roboneuro assign @pbellec as editor

**Comment by roboneuro** [comment]
OK, the editor is @pbellec

**Comment by pbellec** [comment]
@roboneuro add @agahkarakuzu as reviewer

Pierre Bellec

Associate professor | Professeur agrégé
Psychology Department | Département de Psychologie
Centre de recherche de l'institut Universitaire de gériatrie de Montréal (
CRIUGM <http://www.criugm.qc.ca/>)
Université de Montréal, Montréal, Canada
Phone | Téléphone +1 514 713 5596
Brain | Cerveau, Simulation, Exploration (SIMEXP) lab
<http://simexp-lab.org>

**Comment by roboneuro** [comment]
OK, @agahkarakuzu is now a reviewer

**Comment by agahkarakuzu** [comment]
@roboneuro check repository

**Comment by roboneuro** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.09 s (205.9 files/s, 219386.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Jupyter Notebook                12              0          18122            917
Markdown                         3             40              0             79
Dockerfile                       1              5              3              6
YAML                             1              0              0              3
Bourne Shell                     1              0              0              2
-------------------------------------------------------------------------------
SUM:                            18             45          18125           1007
-------------------------------------------------------------------------------


Statistical information for the repository '1' was gathered on 2020/09/25.
No commited files with the specified extensions were found.
```

**Comment by pbellec** [comment]
@roboneuro invite @anibalsolon as reviewer

**Comment by roboneuro** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@pbellec invite was too kind for roboneuro :) should have said "add"

**Comment by pbellec** [comment]
I'm sorry robot, I am not taking no for an answer. 

@roboneuro add @anibalsolon as reviewer

**Comment by pbellec** [comment]
@roboneuro add @anibalsolon as reviewer

**Comment by roboneuro** [comment]
OK, @anibalsolon is now a reviewer

**Comment by emdupre** [comment]
> I'm sorry robot, I am not taking no for an answer.

:rofl: I can change the commands, too !

**Comment by ltetrel** [comment]
@roboneuro are you human?

**Comment by roboneuro** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro are you there?

**Comment by roboneuro** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro are you deployed from `nl-api` branch?

**Comment by roboneuro** [comment]
I'm sorry dear human, I don't understand that. You can see what commands I support by typing:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
Yes you are 😎

**Comment by ltetrel** [comment]
One of the effects of confinement, people start chatting with robots...
:robot:
