### ISSUE TITLE
[PRE REVIEW]: A database of the healthy human spinal cord morphometry in the PAM50 template space

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#16]
**Submitting author:** @valosekj (<a href="http://orcid.org/0000-0002-7398-4990">Jan Valošek</a>)
**Repository:** https://github.com/valosekj/PAM50-normalized-metrics-paper
**Branch with paper.md** (empty if default branch): main
**Version:** r20230904
**Editor:** @agahkarakuzu
**Reviewers:** @mathieuboudreau
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/764a9031ba7a9108dc07a0da1c09dfbb/status.svg)](https://neurolibre.org/papers/764a9031ba7a9108dc07a0da1c09dfbb)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/764a9031ba7a9108dc07a0da1c09dfbb"><img src="https://neurolibre.org/papers/764a9031ba7a9108dc07a0da1c09dfbb/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/764a9031ba7a9108dc07a0da1c09dfbb/status.svg)](https://neurolibre.org/papers/764a9031ba7a9108dc07a0da1c09dfbb)
```

**Author instructions**

Thanks for submitting your paper to NeuroLibre @valosekj. **Currently, there isn't a NeuroLibre editor assigned** to your paper.

The AEiC suggestion for the handling editor is @agahkarakuzu.

@valosekj if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by agahkarakuzu** [comment]
@roboneuro commands

**Comment by roboneuro** [comment]
Hello @agahkarakuzu, here are the things you can ask me to do:

```

# List all available commands
@roboneuro commands

# Add to this issue's reviewers list
@roboneuro add @username as reviewer

# Remove from this issue's reviewers list
@roboneuro remove @username from reviewers

# Get a list of all editors's GitHub handles
@roboneuro list editors

# Assign a user as the editor of this submission
@roboneuro assign @username as editor

# Remove the editor assigned to this submission
@roboneuro remove editor

# Remind an author, a reviewer or the editor to return to a review after a 
# certain period of time (supported units days and weeks)
@roboneuro remind @reviewer in 2 weeks

# Check the references of the PDF for missing DOIs
@roboneuro check references

# Perform checks on the repository
@roboneuro check repository

# Adds a checklist for the reviewer using this command
@roboneuro generate my checklist

# Set a value for version
@roboneuro set v1.0.0 as version

# Set a value for branch
@roboneuro set neurolibre-paper as branch

# Set a value for repository
@roboneuro set https://github.com/organization/repo as repository

# Set a value for the archive DOI
@roboneuro set set 10.5281/zenodo.6861996 as archive

# Set a value for the (data/book/repository/docker) archive DOI.
@roboneuro set 10.5281/zenodo.6861996 as data archive

# Set executable book URI for the preprint.
@roboneuro set book uri

# Mention the EiCs for the correct track
@roboneuro ping track-eic

# Reject paper
@roboneuro reject

# Withdraw paper
@roboneuro withdraw

# Invite an editor to edit a submission (sending them an email)
@roboneuro invite @(.*) as editor

# Generates the pdf paper
@roboneuro generate pdf

# Recommends the submission for acceptance
@roboneuro recommend-accept

# Accept and publish the paper
@roboneuro accept

# Update data on an accepted/published paper
@roboneuro reaccept

# Generates a LaTeX preprint file
@roboneuro generate preprint

# Flag submission with questionable scope
@roboneuro query scope

# Get a link to the complete list of reviewers
@roboneuro list reviewers

# Creates a post-review checklist with editor and authors tasks
@roboneuro create post-review checklist

# Open the review issue
@roboneuro start review

# Check the status of the NeuroLibre preview server.
@roboneuro preview server status

# Check the status of the NeuroLibre preprint (production) server.
@roboneuro preprint server status

# Build a NeuroLibre reproducible preprint for technical screening.
@roboneuro build book

# After screening, build book from the forked reository.
@roboneuro production build book

# Transfer data from preview to the preprint (production) server.
@roboneuro production sync data

# Transfer the final preprint (forked repo) to the preprint (production) server (DOI URL).
@roboneuro production sync book

# Start the production process by forking repository and configuring it.
@roboneuro production start

# Creates Zenodo deposits (a.k.a buckets) for archiving reproducibility assets.
@roboneuro zenodo create buckets

# Status check for the archival of the reproducibility assets.
@roboneuro zenodo status

# Copy summary PDF from the preprints repository to the NeuroLibre production server.
@roboneuro production sync pdf

# Upload the latest Jupyter Book to Zenodo for archival.
@roboneuro zenodo upload book

# Upload the latest version of the book repository to Zenodo for archival.
@roboneuro zenodo upload repository

# Upload the latest version of the docker image to Zenodo for archival.
@roboneuro zenodo upload docker

# Publish reproducibility assets on Zenodo. Sets DOIs if successful.
@roboneuro zenodo publish

```

**Comment by agahkarakuzu** [comment]
@roboneuro preview server status

**Comment by roboneuro** [comment]
Can't perform this without reviewers

**Comment by agahkarakuzu** [comment]
@roboneuro add @mathieuboudreau as reviewer

**Comment by roboneuro** [comment]
Can't add reviewers: There is no editor assigned yet

**Comment by agahkarakuzu** [comment]
@roboneuro assign @agahkarakuzu as editor

**Comment by roboneuro** [comment]
Assigned! @agahkarakuzu is now the editor

**Comment by agahkarakuzu** [comment]
@roboneuro add @mathieuboudreau as reviewer

**Comment by roboneuro** [comment]
@mathieuboudreau added to the reviewers list!

**Comment by agahkarakuzu** [comment]
@roboneuro preview server status

**Comment by roboneuro** [comment]
&#128994; NeuroLibre server is active (running). <br> &#127808; Ready to accept requests from Issue #16 <br> &#128279; URL: https://preview.neurolibre.org

**Comment by agahkarakuzu** [comment]
@roboneuro build book

**Comment by roboneuro** [comment]
Requested branch/SHA does not exist for https://github.com/valosekj/PAM50-normalized-metrics-paper/

**Comment by agahkarakuzu** [comment]
@roboneuro build book

**Comment by roboneuro** [comment]
&#9899;  **Book Build (Preview)** 
 ---------------------------- 
  **Status:** Waiting for task assignment 
 **Last updated:** 2023-09-07 06:40:01 PDT

**Comment by roboneuro** [comment]
https://preview.neurolibre.org/book-artifacts/valosekj/github.com/PAM50-normalized-metrics-paper/786f9a3aa69365b57f42174356bb9918951542db/_build/html/

**Comment by agahkarakuzu** [comment]
@valosekj thank you so much for the submission! 

I started some tasks to check the status of the PDF build (succeeds, there's an issue with the template on our end, I'll revert the funny author names section) as well as the jupyter book build (in progress). 

I see that the GitHub action to build jupyter book is never triggered, I guess because you have not pushed to main since you added main.yml. 

Also, I deleted the trailing `/` from the repository URL you provided during submission. I'll add a check to the submission system to deal with that automatically in future submissions https://github.com/neurolibre/neurolibre-neo/issues/10, thanks!

**Comment by agahkarakuzu** [comment]
OK, looks like the data location and the code are functional! I was able to generate tables and figures on Binder. To render plotly outputs in Jupyter Book, you need something like the following 

```python
from IPython.display import display, HTML
from plotly.offline import plot

my_table = table_demographic_characteristics(path_csv)
plot(my_table, filename = 'table1.html')
display(HTML('table1.html'))
``` 

I guess the function `table_demographic_characteristics` is not returning a plotly object, but the same pattern should work for `create_subplot(df)`.

**Comment by valosekj** [comment]
> To render plotly outputs in Jupyter Book, you need something like the following
> 
> ```python
> from IPython.display import display, HTML
> from plotly.offline import plot
> 
> my_table = table_demographic_characteristics(path_csv)
> plot(my_table, filename = 'table1.html')
> display(HTML('table1.html'))
> ```

Good catch! Thanks! I fixed this in https://github.com/spinalcordtoolbox/PAM50-normalized-metrics/commit/192d0afd8ed4bcc76b77f925cc17f609710e0887 and https://github.com/valosekj/PAM50-normalized-metrics-paper/commit/e62f9ea0692cca75467fa83c6870b5860243d1ad.

**Comment by valosekj** [comment]
> I see that the GitHub action to build jupyter book is never triggered, I guess because you have not pushed to main since you added main.yml.

Okay, after the [last push](https://github.com/valosekj/PAM50-normalized-metrics-paper/commit/e62f9ea0692cca75467fa83c6870b5860243d1ad) to main, the GitHub action has been triggered but [failed](https://github.com/valosekj/PAM50-normalized-metrics-paper/actions/runs/6122687197/job/16619009120#step:8:186) on the permission issue during cloning of the https://github.com/valosekj/PAM50-normalized-metrics-paper.git/ repo, which is strange because the repo is public and the link works for me.

**Comment by valosekj** [comment]
Also, I do not know if this is relevant, but I specified a particular release (r20230904) during the submission, which is no longer applicable after the [recent commit](https://github.com/valosekj/PAM50-normalized-metrics-paper/commit/e62f9ea0692cca75467fa83c6870b5860243d1ad).

**Comment by valosekj** [comment]
Do you know how to include chapter headings in the left sidebar? Currently, only `Abstract` is included, but I use `#` also for all other headings in my [content/index.ipynb](https://github.com/valosekj/PAM50-normalized-metrics-paper/blob/main/content/index.ipynb).

<img width="800" alt="image" src="https://github.com/neurolibre/neurolibre-reviews/assets/39456460/a2cb1398-cf40-4985-afe9-3263a388032c">

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/neurolibre/preprints/neurolibre.00016/neurolibre.00016/10.55458.neurolibre.00016.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/neurolibre/preprints/blob/neurolibre.00016/neurolibre.00016/10.55458.neurolibre.00016.pdf) :page_facing_up: :point_left:

**Comment by agahkarakuzu** [comment]
@valosekj in single page format we would like to get rid of the sidebar as in https://rrsg2020.github.io/paper/. 

To do that, it takes a tiny modification. IIRC:

```yaml
only_build_toc_files: true
```

Pinging @mathieuboudreau to confirm. 

Also in the summary PDF, looks like there are some WIP sections, can you please go through them?

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/neurolibre/preprints/neurolibre.00016/neurolibre.00016/10.55458.neurolibre.00016.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/neurolibre/preprints/blob/neurolibre.00016/neurolibre.00016/10.55458.neurolibre.00016.pdf) :page_facing_up: :point_left:

**Comment by valosekj** [comment]
> @valosekj in single page format we would like to get rid of the sidebar as in https://rrsg2020.github.io/paper/.
> 
> To do that, it takes a tiny modification. IIRC:
> 
> ```yaml
> only_build_toc_files: true
> ```

Okay! Done in https://github.com/valosekj/PAM50-normalized-metrics-paper/commit/d5459f80d4bac97d7f1ff21437d0013af018e053.

> Also in the summary PDF, looks like there are some WIP sections, can you please go through them?

Thanks for pointing this out! The WIP sections (TODOs) are about adding a link to the interactive preprint to [paper.md](https://github.com/valosekj/PAM50-normalized-metrics-paper/blob/main/paper.md) and [content/index.ipynb](https://github.com/valosekj/PAM50-normalized-metrics-paper/blob/main/content/index.ipynb). Is there already a permanent link that won't change in the future that I could use?

**Comment by agahkarakuzu** [comment]
@roboneuro build book

**Comment by roboneuro** [comment]
&#9899;  **Book Build (Preview)** 
 ---------------------------- 
  **Status:** Waiting for task assignment 
 **Last updated:** 2023-09-28 10:20:08 PDT

**Comment by agahkarakuzu** [comment]
> Thanks for pointing this out! The WIP sections (TODOs) are about adding a link to the interactive preprint to [paper.md](https://github.com/valosekj/PAM50-normalized-metrics-paper/blob/main/paper.md) and [content/index.ipynb](https://github.com/valosekj/PAM50-normalized-metrics-paper/blob/main/content/index.ipynb). Is there already a permanent link that won't change in the future that I could use?

@valosekj The PDF template itself has already a link to the reproducible preprint (on the left column): https://github.com/neurolibre/preprints/blob/neurolibre.00016/neurolibre.00016/10.55458.neurolibre.00016.pdf

They will resolve into DOI-formatted proper URLs upon publishing. So no need to duplicate it unless you want to. In that case the URL will be: https://preprint.neurolibre.org/10.55458/neurolibre.00016

**Comment by roboneuro** [comment]
https://preview.neurolibre.org/book-artifacts/valosekj/github.com/PAM50-normalized-metrics-paper/d5459f80d4bac97d7f1ff21437d0013af018e053/_build/html/

**Comment by agahkarakuzu** [comment]
@valosekj the book build succeeds and the interactive figures are now rendered, thank you!! 

Can you tag the code cells as described below so that they become collapsable in the jupyter book: 

https://jupyterbook.org/en/stable/content/metadata.html#jupyter-cell-tags

Also, can you change the jupyter-book requirement version to `jupyter-book==0.14.0` and I'll see if it gets rid of that sidebar.

**Comment by valosekj** [comment]
> > Thanks for pointing this out! The WIP sections (TODOs) are about adding a link to the interactive preprint to [paper.md](https://github.com/valosekj/PAM50-normalized-metrics-paper/blob/main/paper.md) and [content/index.ipynb](https://github.com/valosekj/PAM50-normalized-metrics-paper/blob/main/content/index.ipynb). Is there already a permanent link that won't change in the future that I could use?
> 
> @valosekj The PDF template itself has already a link to the reproducible preprint (on the left column): https://github.com/neurolibre/preprints/blob/neurolibre.00016/neurolibre.00016/10.55458.neurolibre.00016.pdf
> 
> They will resolve into DOI-formatted proper URLs upon publishing. So no need to duplicate it unless you want to. In that case the URL will be: https://preprint.neurolibre.org/10.55458/neurolibre.00016

Okay! Resolved in https://github.com/valosekj/PAM50-normalized-metrics-paper/commit/818b217f7dfca0fc05384bac36edf2d7a4404df8.

> Can you tag the code cells as described below so that they become collapsable in the jupyter book:

Done in https://github.com/valosekj/PAM50-normalized-metrics-paper/commit/c24057cad2cd8a47371e9966be953f8c254d1afa.

> Also, can you change the jupyter-book requirement version to jupyter-book==0.13.0 and I'll see if it gets rid of that sidebar.

Sure! Done in https://github.com/valosekj/PAM50-normalized-metrics-paper/commit/4094a084f2015d02863f1a4842c007ef0be81fac.

**Comment by agahkarakuzu** [comment]
@roboneuro build book

**Comment by roboneuro** [comment]
&#9899;  **Book Build (Preview)** 
 ---------------------------- 
  **Status:** Waiting for task assignment 
 **Last updated:** 2023-09-28 12:56:47 PDT

**Comment by roboneuro** [comment]
https://preview.neurolibre.org/book-artifacts/valosekj/github.com/PAM50-normalized-metrics-paper/4871821464f73a6cc7662cbf4b8f55a46535106c/_build/_page/index/

**Comment by agahkarakuzu** [comment]
Perfect! Now I'll move this to actual review.

**Comment by agahkarakuzu** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/17.
