### ISSUE TITLE
[PRE REVIEW]: A scoping review of reproducible research practices in MRI

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#20]
**Submitting author:** @agahkarakuzu (<a href="http://orcid.org/0000-0001-7283-271X">Agah Karakuzu</a>)
**Repository:** https://github.com/agahkarakuzu/mriscope
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @pbellec
**Reviewers:** @agahkarakuzu
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/a54aeb597088ea358eeedce57e7f3285/status.svg)](https://neurolibre.org/papers/a54aeb597088ea358eeedce57e7f3285)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/a54aeb597088ea358eeedce57e7f3285"><img src="https://neurolibre.org/papers/a54aeb597088ea358eeedce57e7f3285/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/a54aeb597088ea358eeedce57e7f3285/status.svg)](https://neurolibre.org/papers/a54aeb597088ea358eeedce57e7f3285)
```

**Author instructions**

Thanks for submitting your paper to NeuroLibre @agahkarakuzu. **Currently, there isn't a NeuroLibre editor assigned** to your paper.

The AEiC suggestion for the handling editor is @pbellec.

@agahkarakuzu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro assign @pbellec as editor

**Comment by roboneuro** [comment]
Assigned! @pbellec is now the editor

**Comment by agahkarakuzu** [comment]
@roboneuro add @agahkarakuzu as reviewer

**Comment by roboneuro** [comment]
@agahkarakuzu added to the reviewers list!

**Comment by agahkarakuzu** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/neurolibre/neurolibre-reviews/issues/21.
