### ISSUE TITLE
[PRE REVIEW]: Paper is not enough: Crowdsourcing the T1 mapping common ground via the ISMRM reproducibility challenge

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#22]
**Submitting author:** @mathieuboudreau (<a href="http://orcid.org/0000-0002-7726-4456">Mathieu Boudreau</a>)
**Repository:** https://www.github.com/rrsg2020/note
**Branch with paper.md** (empty if default branch): main
**Version:** v1.0.0
**Editor:** @pbellec
**Reviewers:** @pbellec
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/990f8547642cb2ae8b06be85acd824c3/status.svg)](https://neurolibre.org/papers/990f8547642cb2ae8b06be85acd824c3)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/990f8547642cb2ae8b06be85acd824c3"><img src="https://neurolibre.org/papers/990f8547642cb2ae8b06be85acd824c3/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/990f8547642cb2ae8b06be85acd824c3/status.svg)](https://neurolibre.org/papers/990f8547642cb2ae8b06be85acd824c3)
```

**Author instructions**

Thanks for submitting your paper to NeuroLibre @mathieuboudreau. **Currently, there isn't a NeuroLibre editor assigned** to your paper.

The AEiC suggestion for the handling editor is @pbellec.

@mathieuboudreau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro assign @pbellec as editor

**Comment by roboneuro** [comment]
Assigned! @pbellec is now the editor

**Comment by agahkarakuzu** [comment]
@roboneuro add @pbellec as reviewer

**Comment by roboneuro** [comment]
@pbellec added to the reviewers list!

**Comment by agahkarakuzu** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/neurolibre/neurolibre-reviews/issues/23.
