### ISSUE TITLE
[PRE REVIEW]: Analysis code for the paper "RF shimming in the cervical spinal cord at 7T"

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#24]
**Submitting author:** @mathieuboudreau (<a href="http://orcid.org/0000-0002-7726-4456">Mathieu Boudreau</a>)
**Repository:** https://github.com/shimming-toolbox/rf-shimming-7t
**Branch with paper.md** (empty if default branch): main
**Version:** r20240214
**Editor:** @pbellec
**Reviewers:** @agahkarakuzu
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/5d2f9af7565d26f243c0d96effaf864a/status.svg)](https://neurolibre.org/papers/5d2f9af7565d26f243c0d96effaf864a)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/5d2f9af7565d26f243c0d96effaf864a"><img src="https://neurolibre.org/papers/5d2f9af7565d26f243c0d96effaf864a/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/5d2f9af7565d26f243c0d96effaf864a/status.svg)](https://neurolibre.org/papers/5d2f9af7565d26f243c0d96effaf864a)
```

**Author instructions**

Thanks for submitting your paper to NeuroLibre @mathieuboudreau. **Currently, there isn't a NeuroLibre editor assigned** to your paper.

@mathieuboudreau if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro assign @pbellec as editor

**Comment by roboneuro** [comment]
Assigned! @pbellec is now the editor

**Comment by agahkarakuzu** [comment]
@roboneuro add @agahkarakuzu as reviewer

**Comment by roboneuro** [comment]
@agahkarakuzu added to the reviewers list!

**Comment by agahkarakuzu** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/neurolibre/neurolibre-reviews/issues/25.
