### ISSUE TITLE
[PRE REVIEW]: Vendor-neutral sequences and its implications for the reproducibility of quantitative MRI 

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#26]
**Submitting author:** @agahkarakuzu (<a href="http://orcid.org/0000-0001-7283-271X">Agah Karakuzu</a>)
**Repository:** https://github.com/qmrlab/VENUS
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @mathieuboudreau
**Reviewers:** @pbellec
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/b5f46fcc74266367b05c56515072a87d/status.svg)](https://neurolibre.org/papers/b5f46fcc74266367b05c56515072a87d)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/b5f46fcc74266367b05c56515072a87d"><img src="https://neurolibre.org/papers/b5f46fcc74266367b05c56515072a87d/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/b5f46fcc74266367b05c56515072a87d/status.svg)](https://neurolibre.org/papers/b5f46fcc74266367b05c56515072a87d)
```

**Author instructions**

Thanks for submitting your paper to NeuroLibre @agahkarakuzu. **Currently, there isn't a NeuroLibre editor assigned** to your paper.

@agahkarakuzu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro assign @mathieuboudreau as editor

**Comment by roboneuro** [comment]
Assigned! @mathieuboudreau is now the editor

**Comment by agahkarakuzu** [comment]
@roboneuro add @pbellec as reviewer

**Comment by roboneuro** [comment]
@pbellec added to the reviewers list!

**Comment by agahkarakuzu** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/neurolibre/neurolibre-reviews/issues/27.
