### ISSUE TITLE
[PRE REVIEW]: Integrating Structural, Functional, and Biochemical Brain Imaging Data with MRShiny Brain - An Interactive Web Application

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#28]
**Submitting author:** @arcj-hub (<a href="http://orcid.org/0000-0001-6651-183X">Jessica Archibald</a>)
**Repository:** https://github.com/arcj-hub/MRShiny-Brain
**Branch with paper.md** (empty if default branch): 
**Version:** 4.3.2 (Rversion)
**Editor:** @agahkarakuzu
**Reviewers:** @agahkarakuzu
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/e247b9a6eb73e2cedddff27d25fa8cad/status.svg)](https://neurolibre.org/papers/e247b9a6eb73e2cedddff27d25fa8cad)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/e247b9a6eb73e2cedddff27d25fa8cad"><img src="https://neurolibre.org/papers/e247b9a6eb73e2cedddff27d25fa8cad/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/e247b9a6eb73e2cedddff27d25fa8cad/status.svg)](https://neurolibre.org/papers/e247b9a6eb73e2cedddff27d25fa8cad)
```

**Author instructions**

Thanks for submitting your paper to NeuroLibre @arcj-hub. **Currently, there isn't a NeuroLibre editor assigned** to your paper.

The AEiC suggestion for the handling editor is @agahkarakuzu.

@arcj-hub if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@arcj-hub thank you for your submission! We will have two different tracks for this submission as you also submitted a dashboard! 

* For the dashboard, I will deal with the deployment on the server side myself.
* For the preprint, after this initial issue, we will start the technical screening, during which we can embed the deployed dashboard in your preprint. 

Can you please change`binder/data_requirement.json` with the following content: 

```
{ "src": "https://drive.google.com/uc?id=1lS19qQULVMbuk18ExFl049pZ4JKOR-Lq",
  "dst": "../data",
  "projectName": "mr_shiny_brain"}
```

The google drive link contains the `data.csv` file, would be good to archive with this submission.

**Comment by agahkarakuzu** [comment]
@roboneuro build pdf

**Comment by roboneuro** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

`@roboneuro commands`

**Comment by agahkarakuzu** [comment]
@roboneuro commands

**Comment by roboneuro** [comment]
Hello @agahkarakuzu, here are the things you can ask me to do:

```

# List all available commands
@roboneuro commands

# Add to this issue's reviewers list
@roboneuro add @username as reviewer

# Remove from this issue's reviewers list
@roboneuro remove @username from reviewers

# Get a list of all editors's GitHub handles
@roboneuro list editors

# Assign a user as the editor of this submission
@roboneuro assign @username as editor

# Remove the editor assigned to this submission
@roboneuro remove editor

# Remind an author, a reviewer or the editor to return to a review after a 
# certain period of time (supported units days and weeks)
@roboneuro remind @reviewer in 2 weeks

# Check the references of the PDF for missing DOIs
@roboneuro check references

# Perform checks on the repository
@roboneuro check repository

# Adds a checklist for the reviewer using this command
@roboneuro generate my checklist

# Set a value for version
@roboneuro set v1.0.0 as version

# Set a value for branch
@roboneuro set neurolibre-paper as branch

# Set a value for repository
@roboneuro set https://github.com/organization/repo as repository

# Set a value for the archive DOI
@roboneuro set set 10.5281/zenodo.6861996 as archive

# Set a value for the (data/book/repository/docker) archive DOI.
@roboneuro set 10.5281/zenodo.6861996 as data archive

# Set executable book URI for the preprint.
@roboneuro set book uri

# Mention the EiCs for the correct track
@roboneuro ping track-eic

# Reject paper
@roboneuro reject

# Withdraw paper
@roboneuro withdraw

# Invite an editor to edit a submission (sending them an email)
@roboneuro invite @(.*) as editor

# Generates the pdf paper
@roboneuro generate pdf

# Recommends the submission for acceptance
@roboneuro recommend-accept

# Accept and publish the paper
@roboneuro accept

# Update data on an accepted/published paper
@roboneuro reaccept

# Generates a LaTeX preprint file
@roboneuro generate preprint

# Flag submission with questionable scope
@roboneuro query scope

# Get a link to the complete list of reviewers
@roboneuro list reviewers

# Creates a post-review checklist with editor and authors tasks
@roboneuro create post-review checklist

# Open the review issue
@roboneuro start review

# Check the status of the NeuroLibre preview server.
@roboneuro preview server status

# Check the status of the NeuroLibre preprint (production) server.
@roboneuro preprint server status

# Build a NeuroLibre reproducible preprint for technical screening.
@roboneuro build book

# After screening, build book from the forked reository.
@roboneuro production build book

# Transfer data from preview to the preprint (production) server.
@roboneuro production sync data

# Transfer the final preprint (forked repo) to the preprint (production) server (DOI URL).
@roboneuro production sync book

# Start the production process by forking repository and configuring it.
@roboneuro production start

# Creates Zenodo deposits (a.k.a buckets) for archiving reproducibility assets.
@roboneuro zenodo create buckets

# Status check for the archival of the reproducibility assets.
@roboneuro zenodo status

# Copy summary PDF from the preprints repository to the NeuroLibre production server.
@roboneuro production sync pdf

# Upload the latest Jupyter Book to Zenodo for archival.
@roboneuro zenodo upload book

# Upload the latest version of the book repository to Zenodo for archival.
@roboneuro zenodo upload repository

# Upload the latest version of the docker image to Zenodo for archival.
@roboneuro zenodo upload docker

# Upload the submission data to Zenodo for archival. Will not take effect if the data is already archived.
@roboneuro zenodo upload data

# DESTRUCTIVE ACTION: Deletes zenodo records and all the data that has been uploaded. Cannot perform after zenodo publish.
@roboneuro zenodo flush

# Publish reproducibility assets on Zenodo. Sets DOIs if successful.
@roboneuro zenodo publish

# Build an extended PDF for the target repository.
@roboneuro build extended pdf

# Download the submission data.
@roboneuro cache data

```

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by agahkarakuzu** [comment]
@roboneuro assign @agahkarakuzu as editor

**Comment by roboneuro** [comment]
Assigned! @agahkarakuzu is now the editor

**Comment by agahkarakuzu** [comment]
@roboneuro add @agahkarakuzu as reviewer

**Comment by roboneuro** [comment]
@agahkarakuzu added to the reviewers list!

**Comment by roboneuro** [comment]
:warning: [An error happened when generating the pdf](https://github.com/neurolibre/preprints/actions/runs/10184959189?check_suite_focus=true).

**Comment by agahkarakuzu** [comment]
@arcj-hub also the pdf build threw the following error:

```
 Author (Paulina S. Scheuren) is missing affiliation 
```

Can you fix it on your `paper.md`?

**Comment by arcj-hub** [comment]
I made the changes you requested. Thank you! Wow roboneuro is super cool.


Jessica Archibald, PhD
Postdoctoral Fellow, Department of Radiology

Weill Cornell Medicine
Department of Radiology
407 East 61st St
New York, NY 10065
***@***.******@***.***>

From: Agah ***@***.***>
Reply-To: neurolibre/neurolibre-reviews ***@***.***>
Date: Wednesday, July 31, 2024 at 11:40 AM
To: neurolibre/neurolibre-reviews ***@***.***>
Cc: "Archibald, Jessica" ***@***.***>, Mention ***@***.***>
Subject: Re: [neurolibre/neurolibre-reviews] [PRE REVIEW]: Integrating Structural, Functional, and Biochemical Brain Imaging Data with MRShiny Brain - An Interactive Web Application (Issue #28)

[CAUTION: Non-UBC Email]

@arcj-hub<https://github.com/arcj-hub> also the pdf build threw the following error:

 Author (Paulina S. Scheuren) is missing affiliation

Can you fix it on your paper.md?

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by roboneuro** [comment]
:warning: [An error happened when generating the pdf](https://github.com/neurolibre/preprints/actions/runs/10185721129?check_suite_focus=true).

**Comment by agahkarakuzu** [comment]
@arcj-hub looks like another author is also missing affiliation. Can you fix it and make sure that each author has the affiliations?

```
Author (John L.K Kramer) is missing affiliation 
```

**Comment by arcj-hub** [comment]
It should be good now.

Thanks!

Jessica Archibald, PhD
Postdoctoral Fellow, Department of Radiology

Weill Cornell Medicine
Department of Radiology
407 East 61st St
New York, NY 10065
***@***.******@***.***>



From: Agah ***@***.***>
Reply-To: neurolibre/neurolibre-reviews ***@***.***>
Date: Wednesday, July 31, 2024 at 12:35 PM
To: neurolibre/neurolibre-reviews ***@***.***>
Cc: "Archibald, Jessica" ***@***.***>, Mention ***@***.***>
Subject: Re: [neurolibre/neurolibre-reviews] [PRE REVIEW]: Integrating Structural, Functional, and Biochemical Brain Imaging Data with MRShiny Brain - An Interactive Web Application (Issue #28)

[CAUTION: Non-UBC Email]

@arcj-hub<https://github.com/arcj-hub> looks like another author is also missing affiliation. Can you fix it and make sure that each author has the affiliations?

Author (John L.K Kramer) is missing affiliation

**Comment by agahkarakuzu** [comment]
@roboneuro generate pdf

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/neurolibre/preprints/neurolibre.00028/neurolibre.00028/10.55458.neurolibre.00028.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/neurolibre/preprints/blob/neurolibre.00028/neurolibre.00028/10.55458.neurolibre.00028.pdf) :page_facing_up: :point_left:

**Comment by agahkarakuzu** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/neurolibre/neurolibre-reviews/issues/29.
