### ISSUE TITLE
[PRE REVIEW]: The quest for measuring myelin with MRI - An interactive meta-analysis

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#3]
**Submitting author:** @agahkarakuzu (<a href="http://orcid.org/0000-0001-7283-271X">Agah Karakuzu</a>)
**Repository:** <a href="https://github.com/Notebook-Factory/myelin-meta-analysis" target ="_blank">https://github.com/Notebook-Factory/myelin-meta-analysis</a>
**Editor:** @emdupre
**Reviewers:** @ltetrel
**Managing EiC:** Elizabeth DuPre

**Author instructions**

Thanks for submitting your paper to NeuroLibre @agahkarakuzu.

@agahkarakuzu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://tinyurl.com/y22xx6ux) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by roboneuro** [comment]
Hello human, I'm @roboneuro, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@roboneuro commands
```

**Comment by emdupre** [comment]
@roboneuro assign @emdupre as editor

**Comment by roboneuro** [comment]
OK, the editor is @emdupre

**Comment by emdupre** [comment]
@roboneuro assign @ltetrel as reviewer

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [View built NeuroLibre Notebook](http://neurolibre-data.conp.cloud/book-artifacts/Notebook-Factory/github.com/myelin-meta-analysis/61e33aa234e0aa6c17b2dc0b0988e625f05c0b3f/_build/html/) :page_facing_up::point_left:

**Comment by roboneuro** [comment]
I'm sorry dear human, I don't understand that. You can see what commands I support by typing:

```
@roboneuro commands
```

**Comment by roboneuro** [comment]
Here are some things you can ask me to do:

```
# List all of RoboNeuro's capabilities
@roboneuro commands

# Assign a GitHub user as the sole tester of this submission
@roboneuro assign @username as tester

# Add a GitHub user to the testers of this submission
@roboneuro add @username as tester

# Re-invite a tester (if they can't update checklists)
@roboneuro re-invite @username as tester

# Remove a GitHub user from the testers of this submission
@roboneuro remove @username as tester

# List of manager GitHub usernames
@roboneuro list managers

# List of current testers
@roboneuro list testers

# Change manager assignment
@roboneuro assign @username as manager

# Set the software archive DOI at the top of the issue e.g.
@roboneuro set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@roboneuro set v1.0.1 as version

# Open the review issue
@roboneuro start review

MANAGERIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@roboneuro generate pdf

# Compile the paper from alternative branch
@roboneuro generate pdf from branch custom-branch-name

# Compile the NeuroLibre notebook
@roboneuro generate nl-notebook

# Compile the NeuroLibre notebook from alternative branch
@roboneuro generate nl-notebook from branch custom-branch-name

# Remind an author or tester to return to a review after a
# certain period of time (supported units days and weeks)
@roboneuro remind @tester in 2 days

# Ask RoboNeuro to do a dry run of accepting the paper and depositing with Crossref
@roboneuro accept

# Ask RoboNeuro to check the references for missing DOIs
@roboneuro check references

# Ask RoboNeuro to check repository statistics for the submitted software
@roboneuro check repository

MANAGER-IN-CHIEF TASKS

# Invite an manager to edit a submission (sending them an email)
@roboneuro invite @manager as manager

# Reject a paper
@roboneuro reject

# Withdraw a paper
@roboneuro withdraw

# Ask RoboNeuro to actually accept the paper and deposit with Crossref
@roboneuro accept deposit=true

```

**Comment by roboneuro** [comment]
:point_right::page_facing_up: [View built NeuroLibre Notebook](http://neurolibre-data.conp.cloud/book-artifacts/Notebook-Factory/github.com/myelin-meta-analysis/5bf51523c907cc67ece76d89a9634615c4ccf733/_build/html/) :page_facing_up::point_left:

**Comment by roboneuro** [comment]
&#9899;  **REPRODUCIBLE PREPRINT TRANSFER (Preview --> Preprint)** 
 ---------------------------- 
  **Status:** Waiting for task assignment 
 **Last updated:** 2023-05-19 04:30:50 PDT

**Comment by roboneuro** [comment]
&#9899;  **REPRODUCIBLE PREPRINT TRANSFER (Preview --> Preprint)** 
 ---------------------------- 
  **Status:** Waiting for task assignment 
 **Last updated:** 2023-05-19 04:43:21 PDT

**Comment by roboneuro** [comment]
&#9899;  **REPRODUCIBLE PREPRINT TRANSFER (Preview --> Preprint)** 
 ---------------------------- 
  **Status:** Waiting for task assignment 
 **Last updated:** 2023-05-19 04:51:58 PDT

**Comment by roboneuro** [comment]
&#9899;  **REPRODUCIBLE PREPRINT TRANSFER (Preview --> Preprint)** 
 ---------------------------- 
  **Status:** Waiting for task assignment 
 **Last updated:** 2023-05-19 04:57:09 PDT
