### ISSUE TITLE
[PRE REVIEW]: Little Science, Big Science, and Beyond: How Amateurs Shape the Scientific Landscape

### ISSUE THREAD

**Issue by roboneuro** [neurolibre/neurolibre-reviews#30]
**Submitting author:** @agahkarakuzu (<a href="http://orcid.org/0000-0001-7283-271X">Agah Karakuzu</a>)
**Repository:** https://github.com/agahkarakuzu/amateur-science
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @mathieuboudreau
**Reviewers:** @pbellec
**Managing EiC:** Agah Karakuzu

## Status

[![status](https://neurolibre.org/papers/4525f4ab39fe89daedd9f31402485ffd/status.svg)](https://neurolibre.org/papers/4525f4ab39fe89daedd9f31402485ffd)

Status badge code:

```
HTML: <a href="https://neurolibre.org/papers/4525f4ab39fe89daedd9f31402485ffd"><img src="https://neurolibre.org/papers/4525f4ab39fe89daedd9f31402485ffd/status.svg"></a>
Markdown: [![status](https://neurolibre.org/papers/4525f4ab39fe89daedd9f31402485ffd/status.svg)](https://neurolibre.org/papers/4525f4ab39fe89daedd9f31402485ffd)
```

**Author instructions**

Thanks for submitting your paper to NeuroLibre @agahkarakuzu. **Currently, there isn't a NeuroLibre editor assigned** to your paper.

@agahkarakuzu if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/neurolibre_reviewers) have already agreed to review for NeuroLibre and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The NeuroLibre submission bot @roboneuro is here to help you find and assign reviewers and start the main review. To find out what @roboneuro can do for you type:

```
@roboneuro commands
```

**Comment by agahkarakuzu** [comment]
@roboneuro cache data

**Comment by roboneuro** [comment]
Can't perform this without reviewers

**Comment by agahkarakuzu** [comment]
@roboneuro assign @mathieuboudreau as editor

**Comment by roboneuro** [comment]
Assigned! @mathieuboudreau is now the editor

**Comment by agahkarakuzu** [comment]
@mathieuboudreau add @pbellec as reviewer

**Comment by agahkarakuzu** [comment]
@roboneuro commands

**Comment by roboneuro** [comment]
Hello @agahkarakuzu, here are the things you can ask me to do:

```

# List all available commands
@roboneuro commands

# Add to this issue's reviewers list
@roboneuro add @username as reviewer

# Remove from this issue's reviewers list
@roboneuro remove @username from reviewers

# Get a list of all editors's GitHub handles
@roboneuro list editors

# Assign a user as the editor of this submission
@roboneuro assign @username as editor

# Remove the editor assigned to this submission
@roboneuro remove editor

# Remind an author, a reviewer or the editor to return to a review after a 
# certain period of time (supported units days and weeks)
@roboneuro remind @reviewer in 2 weeks

# Check the references of the PDF for missing DOIs
@roboneuro check references

# Perform checks on the repository
@roboneuro check repository

# Adds a checklist for the reviewer using this command
@roboneuro generate my checklist

# Set a value for version
@roboneuro set v1.0.0 as version

# Set a value for branch
@roboneuro set neurolibre-paper as branch

# Set a value for repository
@roboneuro set https://github.com/organization/repo as repository

# Set a value for the archive DOI
@roboneuro set set 10.5281/zenodo.6861996 as archive

# Set a value for the (data/book/repository/docker) archive DOI.
@roboneuro set 10.5281/zenodo.6861996 as data archive

# Set executable book URI for the preprint.
@roboneuro set book uri

# Mention the EiCs for the correct track
@roboneuro ping track-eic

# Reject paper
@roboneuro reject

# Withdraw paper
@roboneuro withdraw

# Invite an editor to edit a submission (sending them an email)
@roboneuro invite @(.*) as editor

# Builds myst article. First argument is the commit hash, second is the binder hash.
@roboneuro build (\S+) myst at runtime (\S+)

# Generates the pdf paper
@roboneuro generate pdf

# Recommends the submission for acceptance
@roboneuro recommend-accept

# Accept and publish the paper
@roboneuro accept

# Update data on an accepted/published paper
@roboneuro reaccept

# Generates a LaTeX preprint file
@roboneuro generate preprint

# Flag submission with questionable scope
@roboneuro query scope

# Get a link to the complete list of reviewers
@roboneuro list reviewers

# Creates a post-review checklist with editor and authors tasks
@roboneuro create post-review checklist

# Open the review issue
@roboneuro start review

# Check the status of the NeuroLibre preview server.
@roboneuro preview server status

# Check the status of the NeuroLibre preprint (production) server.
@roboneuro preprint server status

# Build a NeuroLibre reproducible preprint for technical screening.
@roboneuro build book

# After screening, build book from the forked reository.
@roboneuro production build book

# Transfer data from preview to the preprint (production) server.
@roboneuro production sync data

# Transfer the final preprint (forked repo) to the preprint (production) server (DOI URL).
@roboneuro production sync book

# Start the production process by forking repository and configuring it.
@roboneuro production start

# Creates Zenodo deposits (a.k.a buckets) for archiving reproducibility assets.
@roboneuro zenodo create buckets

# Status check for the archival of the reproducibility assets.
@roboneuro zenodo status

# Copy summary PDF from the preprints repository to the NeuroLibre production server.
@roboneuro production sync pdf

# Upload the latest Jupyter Book to Zenodo for archival.
@roboneuro zenodo upload book

# Upload the latest version of the book repository to Zenodo for archival.
@roboneuro zenodo upload repository

# Upload the latest version of the docker image to Zenodo for archival.
@roboneuro zenodo upload docker

# Upload the submission data to Zenodo for archival. Will not take effect if the data is already archived.
@roboneuro zenodo upload data

# DESTRUCTIVE ACTION: Deletes zenodo records and all the data that has been uploaded. Cannot perform after zenodo publish.
@roboneuro zenodo flush

# Publish reproducibility assets on Zenodo. Sets DOIs if successful.
@roboneuro zenodo publish

# Build an extended PDF for the target repository.
@roboneuro build extended pdf

# Download the submission data.
@roboneuro cache data

```

**Comment by agahkarakuzu** [comment]
@roboneuro add @pbellec as reviewer

**Comment by roboneuro** [comment]
@pbellec added to the reviewers list!

**Comment by agahkarakuzu** [comment]
@roboneuro cache data

**Comment by roboneuro** [comment]
&#128994; **DOWNLOAD DATA**
----------------------------
**Status:** Success `a5715f19`
**Last updated:** 2024-12-02 15:26:36 PST

<details><summary> :information_source: See details </summary><pre><code>🔰 Downloaded data in /DATA/amateur-science (288.6 MB).
- repo2data_cache_record.json (127 Bytes)
- pat.csv (288.6 MB)</code></pre></details>

**Comment by roboneuro** [comment]
> [!TIP]
> 💽 The data is now available for https://preview.neurolibre.org (to build reproducible ✨MyST✨ preprints) and synced to https://binder-preview.conp.cloud BinderHub cluster (to test live compute).

**Comment by lunebellec** [comment]
@roboneuro build book

**Comment by roboneuro** [comment]
Missing _toc.yml or _config.yml under the content folder.

**Comment by roboneuro** [comment]
&#9898;  **Book Build (Preview)** 
 ---------------------------- 
  **Status:** Assigned to task `4e4f04f9` 
 **Last updated:** 2024-12-02 15:58:23 PST 
  
 :recycle: :recycle: <a href="https://github.com/neurolibre/neurolibre-reviews/issues/30#issuecomment-2513223713">Refresh</a>)

**Comment by agahkarakuzu** [comment]
@pbellec this is myst formatted, that command won't do it :) There's a `pd.groupby` command that'll take some unnecessary time

**Comment by agahkarakuzu** [comment]
@roboneuro build latest myst at runtime latest

**Comment by roboneuro** [comment]
&#128994; **Build MyST article**
----------------------------
**Status:** Success `7737a5c0`
**Last updated:** 2024-12-02 16:00:19 PST

🌺 MyST build succeeded: 

 https://preview.neurolibre.org/myst/agahkarakuzu/amateur-science/5a23f6ee088d3d114ae98181b1a393c1aaf24ebc/_build/html/index.html

**Comment by agahkarakuzu** [comment]
@roboneuro build latest myst at runtime 5a23f6ee088d3d114ae98181b1a393c1aaf24ebc

**Comment by roboneuro** [comment]
&#128994; **Build MyST article**
----------------------------
**Status:** Success `34261d79`
**Last updated:** 2024-12-02 16:04:55 PST

🌺 MyST build succeeded: 

 https://preview.neurolibre.org/myst/agahkarakuzu/amateur-science/37baaef00e8d50795909c0fb723b897c7fcfde9b/_build/html/index.html

**Comment by lunebellec** [comment]
@roboneuro check references

**Comment by agahkarakuzu** [comment]
@roboneuro build latest myst at runtime 5a23f6ee088d3d114ae98181b1a393c1aaf24ebc

**Comment by roboneuro** [comment]
&#128994; **Build MyST article**
----------------------------
**Status:** Success `df2a835f`
**Last updated:** 2024-12-02 16:10:20 PST

🌺 MyST build succeeded: 

 https://preview.neurolibre.org/myst/agahkarakuzu/amateur-science/14047de5461a0aa50387e1ea4302e481c096bd01/_build/html/index.html

**Comment by agahkarakuzu** [comment]
@roboneuro build latest myst at runtime 5a23f6ee088d3d114ae98181b1a393c1aaf24ebc

**Comment by roboneuro** [comment]
&#128992; **Build MyST article**
----------------------------
**Status:** In progress `973322c2`
**Last updated:** 2024-12-02 16:18:44 PST

<details><summary> :information_source: See details </summary><pre><code>Issuing MyST build command, execution environment: binder-registry.conp.cloud/binder-agahkarakuzu-2damateur-2dscience-3fc766</code></pre></details>
:recycle: <a href="https://github.com/neurolibre/neurolibre-reviews/issues/30#issuecomment-2513246489">Refresh</a>

**Comment by agahkarakuzu** [comment]
@roboneuro build latest myst at runtime 5a23f6ee088d3d114ae98181b1a393c1aaf24ebc

**Comment by roboneuro** [comment]
&#128994; **Build MyST article**
----------------------------
**Status:** Success `b85ac76a`
**Last updated:** 2024-12-02 16:33:10 PST

🌺 MyST build succeeded: 

 https://preview.neurolibre.org/myst/agahkarakuzu/amateur-science/b9241915da334c575a77fbb228409d4874bc1eec/_build/html/index.html

**Comment by agahkarakuzu** [comment]
@roboneuro build latest myst at runtime 5a23f6ee088d3d114ae98181b1a393c1aaf24ebc

**Comment by roboneuro** [comment]
&#128994; **Build MyST article**
----------------------------
**Status:** Success `b50d7983`
**Last updated:** 2024-12-02 16:46:56 PST

🌺 MyST build succeeded: 

 https://preview.neurolibre.org/myst/agahkarakuzu/amateur-science/21cbe2cd4081263b16488b9bbd8a49655c4878e1/_build/html/index.html

**Comment by agahkarakuzu** [comment]
@roboneuro start review

**Comment by roboneuro** [comment]
OK, I've started the review over in https://github.com/neurolibre/neurolibre-reviews/issues/31.
